baseURL = "https://akira-kurogane.github.io/mongodb-guide/"
languageCode = "en-US"
defaultContentLanguage = "en"
publishDir = "public"

title = "Akira's MongoDB Guide"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  description = "Akira's guide for MongoDB"
  author = "Akira Kurogane"
  showVisitedLinks = true
  disableInlineCopyToClipBoard = true
  themeVariant = "green"
  # Disable search function. It will hide search bar
  disableSearch = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
  smartypants = false

[Languages]
[Languages.en]
title = "Akira's MongoDB Guide"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/akira-kurogane/mongodb-guide"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Theme credits"
url = "/credits"
weight = 30

[Languages.ja]
title = "アキラのMongoDBガイド"
weight = 2
languageName = "日本語"

[[Languages.ja.menu.shortcuts]]
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/akira-kurogane/mongodb-guide"
weight = 10

[[Languages.ja.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Theme クレジット"
url = "/credits"
weight = 30
