baseURL = "localhost:1313"
languageCode = "en-US"
defaultContentLanguage = "en"
publishDir = "docs"

title = "Akira's MongoDB Guide"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  description = "Akira's guide for MongoDB"
  author = "Mathieu Cornic"
  showVisitedLinks = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Akira's MongoDB Guide"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/akira-kurogane/mongodb-guide"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Theme credits"
url = "/credits"
weight = 30

[Languages.ja]
title = "アキラのMongoDBガイド"
weight = 2
languageName = "日本語"

[[Languages.ja.menu.shortcuts]]
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/akira-kurogane/mongodb-guide"
weight = 10

[[Languages.ja.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Theme クレジット"
url = "/credits"
weight = 30
